Repository DS-StoryTeller/back-end, pull requests merged in 2024-09, with the labels that each got.

#59 ✨ Feat: process kakao user
  build.gradle
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/config/SecurityConfig.java
  src/main/java/com/cojac/storyteller/controller/UserController.java
  src/main/java/com/cojac/storyteller/domain/SocialUserEntity.java
  src/main/java/com/cojac/storyteller/dto/user/KakaoLoginRequestDTO.java
  src/main/java/com/cojac/storyteller/dto/user/SocialUserDTO.java
  src/main/java/com/cojac/storyteller/service/UserService.java
Labels: :sparkles: Feat

#60 ✨ Feat: swagger setup
  src/main/java/com/cojac/storyteller/code/ErrorCode.java
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/config/SecurityConfig.java
  src/main/java/com/cojac/storyteller/config/swagger/LoginSwaggerConfig.java
  src/main/java/com/cojac/storyteller/config/swagger/LogoutSwaggerConfig.java
  src/main/java/com/cojac/storyteller/config/swagger/SwaggerConfig.java
  src/main/java/com/cojac/storyteller/controller/BookController.java
  src/main/java/com/cojac/storyteller/controller/PageController.java
  src/main/java/com/cojac/storyteller/controller/ProfileController.java
  src/main/java/com/cojac/storyteller/controller/SettingController.java
  src/main/java/com/cojac/storyteller/controller/UnknownWordController.java
  src/main/java/com/cojac/storyteller/controller/UserController.java
  src/main/java/com/cojac/storyteller/docs/BookControllerDocs.java
  src/main/java/com/cojac/storyteller/docs/PageControllerDocs.java
  src/main/java/com/cojac/storyteller/docs/ProfileControllerDocs.java
  src/main/java/com/cojac/storyteller/docs/SettingControllerDocs.java
  src/main/java/com/cojac/storyteller/docs/UnknownWordControllerDocs.java
  src/main/java/com/cojac/storyteller/docs/UserControllerDocs.java
  src/main/java/com/cojac/storyteller/domain/ProfileEntity.java
  src/main/java/com/cojac/storyteller/dto/profile/UpdateProfileDTO.java
  src/main/java/com/cojac/storyteller/dto/user/CreateUserRequestDTO.java
  src/main/java/com/cojac/storyteller/dto/user/UsernameDTO.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/PageService.java
  src/main/java/com/cojac/storyteller/service/ProfileService.java
  src/main/java/com/cojac/storyteller/service/UserService.java
Labels: :bug: Fix, :sparkles: Feat, 🛠️ Chore

#72 ⚙Setting: jmeter load test
  build.gradle
  src/main/java/com/cojac/storyteller/config/SecurityConfig.java
Labels: ⚙ Setting

#73 ✨Feat: Actuator 경로 수정
  src/main/java/com/cojac/storyteller/config/SecurityConfig.java
Labels: :sparkles: Feat

#74 ✨Feat: 보안적인 측면에서 경로 노출 안되게 수정
  src/main/java/com/cojac/storyteller/config/SecurityConfig.java
Labels: :sparkles: Feat

#75 ✨Feat: optimize book list
  .gitignore
  src/main/java/com/cojac/storyteller/config/SecurityConfig.java
  src/main/java/com/cojac/storyteller/config/swagger/SwaggerConfig.java
  src/main/java/com/cojac/storyteller/controller/BookController.java
  src/main/java/com/cojac/storyteller/docs/BookControllerDocs.java
  src/main/java/com/cojac/storyteller/domain/BookEntity.java
  src/main/java/com/cojac/storyteller/performance/PerformanceConfig.java
  src/main/java/com/cojac/storyteller/performance/PerformanceInterceptor.java
  src/main/java/com/cojac/storyteller/performance/PerformanceMonitor.java
  src/main/java/com/cojac/storyteller/performance/PerformanceMonitorAop.java
  src/main/java/com/cojac/storyteller/performance/ProxyConnectionHandler.java
  src/main/java/com/cojac/storyteller/performance/ProxyPreparedStatementHandler.java
  src/main/java/com/cojac/storyteller/repository/BookRepository.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/mapper/BookMapper.java
Labels: :sparkles: Feat

#79 ✨Feat: optimize query
  src/main/java/com/cojac/storyteller/repository/PageRepository.java
  src/main/java/com/cojac/storyteller/repository/ProfileRepository.java
  src/main/java/com/cojac/storyteller/repository/batch/BatchBookDelete.java
  src/main/java/com/cojac/storyteller/repository/batch/BatchProfileDelete.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/PageService.java
  src/main/java/com/cojac/storyteller/service/ProfileService.java
  src/main/java/com/cojac/storyteller/service/UnknownWordService.java
Labels: :sparkles: Feat, :recycle: Refactor

#71 ✨ Feat: optimize create book
  src/main/java/com/cojac/storyteller/domain/BookEntity.java
  src/main/java/com/cojac/storyteller/repository/PageBatchRepository.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/OpenAIService.java
  src/main/java/com/cojac/storyteller/service/mapper/BookMapper.java
Labels: :bug: Fix

#81 🐛 !Hotfix: DB 테이블명 대소문자 구분하여 다시 구성
  src/main/java/com/cojac/storyteller/repository/batch/BatchBookDelete.java
  src/main/java/com/cojac/storyteller/repository/batch/BatchPageInsert.java
  src/main/java/com/cojac/storyteller/repository/batch/BatchProfileDelete.java
  src/main/java/com/cojac/storyteller/service/BookService.java
Labels: :bug: Fix

#82 🐛 HotFix: DB 테이블명 수정
  src/main/java/com/cojac/storyteller/repository/batch/BatchBookDelete.java
  src/main/java/com/cojac/storyteller/repository/batch/BatchProfileDelete.java
Labels: :bug: Fix

#83 ✨Feat: S3 이미지 삭제 로직 추가
  src/main/java/com/cojac/storyteller/controller/BookController.java
  src/main/java/com/cojac/storyteller/controller/ProfileController.java
  src/main/java/com/cojac/storyteller/docs/BookControllerDocs.java
  src/main/java/com/cojac/storyteller/docs/ProfileControllerDocs.java
  src/main/java/com/cojac/storyteller/repository/BookRepository.java
  src/main/java/com/cojac/storyteller/service/AmazonS3Service.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/ProfileService.java
Labels: :sparkles: Feat

#84 fix: 동화 이미지 중복 생성 문제 해결
  src/main/java/com/cojac/storyteller/service/BookService.java
Labels: :bug: Fix
