Repository DS-StoryTeller/back-end, pull requests merged in 2024-07, with the labels that each got.

#33 ✨ openAI API를 사용한 동화 퀴즈 생성
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/controller/BookController.java
  src/main/java/com/cojac/storyteller/dto/book/QuizResponseDTO.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/OpenAIService.java
Labels: :bug: Fix, :sparkles: Feat, :recycle: Refactor

#38 ✨ Feat: 책 즐겨찾기, 읽는 중 필터링
  build.gradle
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/controller/BookController.java
  src/main/java/com/cojac/storyteller/repository/BookRepository.java
  src/main/java/com/cojac/storyteller/service/BookService.java
Labels: :sparkles: Feat

#37 ✨ Feat: profile managment
  src/main/java/com/cojac/storyteller/code/ErrorCode.java
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/controller/ProfileController.java
  src/main/java/com/cojac/storyteller/domain/LocalUserEntityEntity.java
  src/main/java/com/cojac/storyteller/domain/ProfileEntity.java
  src/main/java/com/cojac/storyteller/domain/SocialUserEntityEntity.java
  src/main/java/com/cojac/storyteller/domain/UserEntity.java
  src/main/java/com/cojac/storyteller/dto/profile/PinNumberDTO.java
  src/main/java/com/cojac/storyteller/dto/profile/ProfileDTO.java
  src/main/java/com/cojac/storyteller/dto/profile/ProfilePhotoDTO.java
  src/main/java/com/cojac/storyteller/dto/user/CustomUserDetails.java
  src/main/java/com/cojac/storyteller/exception/GlobalExceptionHandler.java
  src/main/java/com/cojac/storyteller/exception/InvalidPinNumberException.java
  src/main/java/com/cojac/storyteller/exception/UserNotFoundException.java
  src/main/java/com/cojac/storyteller/jwt/JWTFilter.java
  src/main/java/com/cojac/storyteller/repository/ProfileRepository.java
  src/main/java/com/cojac/storyteller/repository/SocialUserRepository.java
  src/main/java/com/cojac/storyteller/repository/UserRepository.java
  src/main/java/com/cojac/storyteller/service/AmazonS3Service.java
  src/main/java/com/cojac/storyteller/service/CustomOAuth2UserService.java
  src/main/java/com/cojac/storyteller/service/CustomUserDetailsService.java
  src/main/java/com/cojac/storyteller/service/ProfileService.java
  src/main/java/com/cojac/storyteller/service/UserService.java
  src/main/java/com/cojac/storyteller/service/mapper/ProfileService.java
  src/test/java/com/cojac/storyteller/service/AmazonS3ServiceTest.java
  src/test/java/com/cojac/storyteller/service/ProfileServiceTest.java
Labels: :bug: Fix, :sparkles: Feat, :recycle: Refactor, ✅ Test

#46 Fix: 색 설정 변경 시 fontSize와 readingSpeed 중 하나의 값만 전달해도 수정 가능하도록 변경
  src/main/java/com/cojac/storyteller/domain/SettingEntity.java
  src/main/java/com/cojac/storyteller/service/SettingService.java
Labels: :bug: Fix

#45 Feature/#43 book isreading
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/controller/BookController.java
  src/main/java/com/cojac/storyteller/domain/BookEntity.java
  src/main/java/com/cojac/storyteller/dto/book/BookListResponseDTO.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/mapper/BookMapper.java
Labels: :bug: Fix, :sparkles: Feat

#47 🐛 Fix: 회원가입 로직 수정
  build.gradle
  src/main/java/com/cojac/storyteller/StorytellerApplication.java
  src/main/java/com/cojac/storyteller/annotation/AtLeastOneNotNull.java
  src/main/java/com/cojac/storyteller/annotation/AtLeastOneNotNullValidator.java
  src/main/java/com/cojac/storyteller/code/ErrorCode.java
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/config/EmailConfig.java
  src/main/java/com/cojac/storyteller/config/RedisConfig.java
  src/main/java/com/cojac/storyteller/config/SecurityConfig.java
  src/main/java/com/cojac/storyteller/controller/LoginController.java
  src/main/java/com/cojac/storyteller/controller/ProfileController.java
  src/main/java/com/cojac/storyteller/controller/UserController.java
  src/main/java/com/cojac/storyteller/domain/LocalUserEntity.java
  src/main/java/com/cojac/storyteller/domain/RefreshEntity.java
  src/main/java/com/cojac/storyteller/domain/SocialUserEntity.java
  src/main/java/com/cojac/storyteller/domain/SocialUserEntityEntity.java
  src/main/java/com/cojac/storyteller/dto/response/ErrorResponseDTO.java
  src/main/java/com/cojac/storyteller/dto/user/CustomUserDetails.java
  src/main/java/com/cojac/storyteller/dto/user/EmailDTO.java
  src/main/java/com/cojac/storyteller/dto/user/LocalUserDTO.java
  src/main/java/com/cojac/storyteller/dto/user/ReissueDTO.java
  src/main/java/com/cojac/storyteller/dto/user/SocialUserDTO.java
  src/main/java/com/cojac/storyteller/dto/user/UserDTO.java
  src/main/java/com/cojac/storyteller/dto/user/UsernameDTO.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/CustomOAuth2User.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/GoogleResponse.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/KakaoResponse.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/OAuth2Response.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/OAuth2ResponseFactory.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/SocialUserDTO.java
  src/main/java/com/cojac/storyteller/exception/BusinessLogicException.java
  src/main/java/com/cojac/storyteller/exception/DuplicateEmailException.java
  src/main/java/com/cojac/storyteller/exception/EmailSendingException.java
  src/main/java/com/cojac/storyteller/exception/GlobalExceptionHandler.java
  src/main/java/com/cojac/storyteller/exception/RefreshTokenExpiredException.java
  src/main/java/com/cojac/storyteller/exception/UsernameExistsException.java
  src/main/java/com/cojac/storyteller/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/cojac/storyteller/jwt/CustomLogoutFilter.java
  src/main/java/com/cojac/storyteller/jwt/JWTFilter.java
  src/main/java/com/cojac/storyteller/jwt/JWTUtil.java
  src/main/java/com/cojac/storyteller/jwt/LoginFilter.java
  src/main/java/com/cojac/storyteller/jwt/oauth2/CustomSuccessHandler.java
  src/main/java/com/cojac/storyteller/repository/LocalUserRepository.java
  src/main/java/com/cojac/storyteller/repository/RefreshRedisRepository.java
  src/main/java/com/cojac/storyteller/repository/SocialUserRepository.java
  src/main/java/com/cojac/storyteller/repository/UserRepository.java
  src/main/java/com/cojac/storyteller/service/CustomOAuth2UserService.java
  src/main/java/com/cojac/storyteller/service/CustomUserDetailsService.java
  src/main/java/com/cojac/storyteller/service/MailService.java
  src/main/java/com/cojac/storyteller/service/OpenAIService.java
  src/main/java/com/cojac/storyteller/service/ProfileService.java
  src/main/java/com/cojac/storyteller/service/RedisService.java
  src/main/java/com/cojac/storyteller/service/UserService.java
  src/main/resources/templates/login.html
  src/test/java/com/cojac/storyteller/repository/RefreshRedisRepositoryTest.java
  src/test/java/com/cojac/storyteller/service/ProfileServiceTest.java
  src/test/java/com/cojac/storyteller/service/RedisServiceTest.java
Labels: :bug: Fix, :sparkles: Feat, :recycle: Refactor, 🛠️ Chore

#48 ✨Feat: profile managment
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/controller/ProfileController.java
  src/main/java/com/cojac/storyteller/domain/ProfileEntity.java
  src/main/java/com/cojac/storyteller/dto/profile/PinCheckResultDTO.java
  src/main/java/com/cojac/storyteller/dto/profile/PinNumberDTO.java
  src/main/java/com/cojac/storyteller/dto/profile/ProfileDTO.java
  src/main/java/com/cojac/storyteller/service/ProfileService.java
  src/test/java/com/cojac/storyteller/service/ProfileServiceTest.java
Labels: :sparkles: Feat, :recycle: Refactor, 🛠️ Chore

#49 ✨ Feat: unknownWord 저장 시 생성한 unknownword의 id 값 응답에 추가
  src/main/java/com/cojac/storyteller/controller/UnknownWordController.java
  src/main/java/com/cojac/storyteller/dto/page/PageDetailResponseDTO.java
  src/main/java/com/cojac/storyteller/dto/unknownWord/UnknownWordDTO.java
  src/main/java/com/cojac/storyteller/dto/unknownWord/UnknownWordDetailDTO.java
  src/main/java/com/cojac/storyteller/service/PageService.java
  src/main/java/com/cojac/storyteller/service/UnknownWordService.java
Labels: :sparkles: Feat, :recycle: Refactor
