Repository DS-StoryTeller/back-end, pull requests merged in 2024-05, with the labels that each got.

#15 :bug: Fix: 개발편의를 위해 Access 토큰 유효기간 24시간으로 변경
  src/main/java/com/cojac/storyteller/controller/UserController.java
  src/main/java/com/cojac/storyteller/jwt/LoginFilter.java
Labels: :bug: Fix

#13 :sparkles: Feature: 동화 및 페이지 조회 및 세부 기능 개발
  src/main/java/com/cojac/storyteller/code/ErrorCode.java
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/controller/BookController.java
  src/main/java/com/cojac/storyteller/controller/PageController.java
  src/main/java/com/cojac/storyteller/domain/BookEntity.java
  src/main/java/com/cojac/storyteller/domain/PageEntity.java
  src/main/java/com/cojac/storyteller/dto/book/BookDetailResponseDTO.java
  src/main/java/com/cojac/storyteller/dto/book/BookListResponseDTO.java
  src/main/java/com/cojac/storyteller/dto/page/PageDTO.java
  src/main/java/com/cojac/storyteller/dto/page/PageDetailResponseDTO.java
  src/main/java/com/cojac/storyteller/exception/BookNotFoundException.java
  src/main/java/com/cojac/storyteller/exception/GlobalExceptionHandler.java
  src/main/java/com/cojac/storyteller/exception/PageNotFoundException.java
  src/main/java/com/cojac/storyteller/repository/BookRepository.java
  src/main/java/com/cojac/storyteller/repository/PageRepository.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/PageService.java
  src/main/java/com/cojac/storyteller/service/mapper/BookMapper.java
Labels: :bug: Fix, :sparkles: Feat, 🛠️ Chore

#19 ✨ Feat: Setting
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/controller/SettingController.java
  src/main/java/com/cojac/storyteller/domain/BookEntity.java
  src/main/java/com/cojac/storyteller/domain/SettingEntity.java
  src/main/java/com/cojac/storyteller/domain/setting/FontSize.java
  src/main/java/com/cojac/storyteller/domain/setting/ReadingSpeed.java
  src/main/java/com/cojac/storyteller/dto/setting/SettingDTO.java
  src/main/java/com/cojac/storyteller/repository/SettingRepository.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/SettingService.java
Labels: :sparkles: Feat, :recycle: Refactor

#21 ✨ Feat: Social Login
  build.gradle
  src/main/java/com/cojac/storyteller/code/ErrorCode.java
  src/main/java/com/cojac/storyteller/config/SecurityConfig.java
  src/main/java/com/cojac/storyteller/controller/LoginController.java
  src/main/java/com/cojac/storyteller/controller/UserController.java
  src/main/java/com/cojac/storyteller/domain/RefreshEntity.java
  src/main/java/com/cojac/storyteller/domain/SocialUserEntity.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/CustomOAuth2User.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/GoogleResponse.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/KakaoResponse.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/OAuth2Response.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/OAuth2ResponseFactory.java
  src/main/java/com/cojac/storyteller/dto/user/oauth2/SocialUserDTO.java
  src/main/java/com/cojac/storyteller/exception/GlobalExceptionHandler.java
  src/main/java/com/cojac/storyteller/exception/SocialUserNotFoundException.java
  src/main/java/com/cojac/storyteller/jwt/JWTFilter.java
  src/main/java/com/cojac/storyteller/jwt/JWTUtil.java
  src/main/java/com/cojac/storyteller/jwt/LoginFilter.java
  src/main/java/com/cojac/storyteller/jwt/oauth2/CustomSuccessHandler.java
  src/main/java/com/cojac/storyteller/repository/SocialUserRepository.java
  src/main/java/com/cojac/storyteller/service/CustomOAuth2UserService.java
  src/main/java/com/cojac/storyteller/service/CustomUserDetailsService.java
  src/main/java/com/cojac/storyteller/util/ErrorResponseUtil.java
  src/main/resources/templates/login.html
Labels: :sparkles: Feat, :recycle: Refactor, 🛠️ Chore

#22 ✨ 책 부가 기능(책 삭제, 페이지 이미지 삽입)
  src/main/java/com/cojac/storyteller/code/ResponseCode.java
  src/main/java/com/cojac/storyteller/controller/BookController.java
  src/main/java/com/cojac/storyteller/controller/PageController.java
  src/main/java/com/cojac/storyteller/domain/PageEntity.java
  src/main/java/com/cojac/storyteller/dto/page/PageDetailResponseDTO.java
  src/main/java/com/cojac/storyteller/service/BookService.java
  src/main/java/com/cojac/storyteller/service/PageService.java
Labels: :bug: Fix, :sparkles: Feat
